---
branches:
  only:
  - master

# https://docs.travis-ci.com/user/multi-os/
matrix:
  include:
    - os: osx
      language: generic
      env:
        - TARGET=localhost
        - CONNECTION=local
        - PYTHONPATH="/Library/Python/2.7/site-packages:$PYTHONPATH"
      install:
        - sudo pip install -U setuptools
        - sudo pip install ansible
        - ansible-galaxy install FGtatsuro.python-requirements
    - os: linux
      dist: trusty
      language: python
      python: 2.7
      services:
        - docker
      addons:
        apt:
          packages:
          - python-pip
      before_script:
        - docker run -it -d --name container python:2 /bin/bash
      after_script:
        - docker rm -f container
      env:
        - TARGET=container
        - CONNECTION=docker
        - EXTRA_VARS="docker_daemon_options='-H fd:// --insecure-registry 192.168.1.1:5000 --insecure-registry 192.168.1.2:5000'"
    - os: linux
      language: python
      python: 2.7
      before_install:
        - rvm install 2.2.3
      env:
        - TARGET=localhost
        - CONNECTION=local
        - EXTRA_VARS="docker_group_append_user='travis' docker_daemon_options='-H fd:// --insecure-registry 192.168.1.1:5000 --insecure-registry 192.168.1.2:5000'"
    - os: linux
      dist: trusty
      language: python
      python: 2.7
      env:
        - TARGET=localhost
        - CONNECTION=local
        - EXTRA_VARS="docker_group_append_user='travis' docker_daemon_options='-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock --insecure-registry 192.168.1.1:5000 --insecure-registry 192.168.1.2:5000'"

# This role needs sudo, thus we can't use the new container infrastructure
# sudo: false
sudo: required

install:
  - pip install ansible
  # Resolve dependencies(When target role isn't installed via Ansible Galaxy, auto resolution of dependencies doesn't occur.)
  - ansible-galaxy install FGtatsuro.python-requirements

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory -l ${TARGET} --connection=${CONNECTION} --extra-vars="${EXTRA_VARS}" -vvvv
  # Workaround: On Ubuntu trusty, /etc/default/docker can't be read by travis user because the mode of this file(root:root) is 640.
  # This fact is no problem in normal case, but affects tests.
  - if [ -e /etc/default/docker ]; then sudo chmod 644 /etc/default/docker; fi
  - bundle install
  - bundle exec rake spec SPEC_TARGET=${TARGET}

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
