---
# https://docs.travis-ci.com/user/multi-os/
matrix:
  include:
    # OSX
    - os: osx
      language: generic
      env:
        - TARGET=localhost
    # Debian
    - os: linux
      dist: trusty
      language: python
      python: 2.7
      services:
        - docker
      addons:
        apt:
          packages:
          - python-pip
      before_script:
        - docker run -it -d --name container ${IMAGE_NAME} /bin/sh
      after_script:
        - docker rm -f container
      env:
        - TARGET=container
        - IMAGE_NAME=fgtatsuro/infra-bridgehead:debian-jessie
    # Alpine Linux
    - os: linux
      dist: trusty
      language: python
      python: 2.7
      services:
        - docker
      addons:
        apt:
          packages:
          - python-pip
      before_script:
        - docker run -it -d --name container ${IMAGE_NAME} /bin/sh
      after_script:
        - docker rm -f container
      env:
        - TARGET=container
        - IMAGE_NAME=fgtatsuro/infra-bridgehead:alpine-3.3
    # Ubuntu 12.04
    - os: linux
      language: python
      python: 2.7
      before_install:
        - rvm install 2.2.3
      env:
        - TARGET=localhost
    # Ubuntu 14.04
    - os: linux
      dist: trusty
      language: python
      python: 2.7
      env:
        - TARGET=localhost

# This role needs sudo, thus we can't use the new container infrastructure
# sudo: false
sudo: required

install:
  - sudo pip install ansible
  # Resolve dependencies(When target role isn't installed via Ansible Galaxy, auto resolution of dependencies doesn't occur.)
  - ansible-galaxy install FGtatsuro.python-requirements

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory -l ${TARGET} --connection=${CONNECTION} -vvvv
  - bundle install
  - bundle exec rake spec SPEC_TARGET=${TARGET}

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
