---
# tasks file for docker_toolbox(On Debian family)
- name: Use latest wget to avoid SSL certificate error on access of following tasks
  apt: name=wget state=latest update_cache=yes cache_valid_time=3600 install_recommends=no
  become: yes
- name: Download install script for Docker Engine
  get_url: url="https://get.docker.com" dest="{{ docker_installscript_tmppath }}"
  register: dl_result
- name: Install Docker Engine
  shell: "sh {{ docker_installscript_tmppath }}"
  become: yes
  when: dl_result.changed
- name: Install Docker Machine
  get_url: url="{{ docker_machine_download_url }}" checksum="sha256:{{ docker_machine_sha256 }}" dest="{{ docker_machine_bin_path }}" mode="0755"
  become: yes
- name: Install Docker Compose
  get_url: url="{{ docker_compose_download_url }}" checksum="sha256:{{ docker_compose_sha256 }}" dest="{{ docker_compose_bin_path }}" mode="0755"
  become: yes

